version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: listless-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - listless-network

volumes:
  mongodb_data:

networks:
  listless-network:
    driver: bridge 