[build]
builder = "nixpacks"

[deploy]
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

# Backend service configuration
[[services]]
name = "listless-backend"
path = "backend"
buildCommand = "npm install && npm run build"
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100

# Frontend service configuration
[[services]]
name = "listless-frontend"
path = "frontend"
buildCommand = "npm install && npm run build"
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
dockerfilePath = "frontend/Dockerfile" 